name: Deploy to Server

on:
  push:
    branches:
      - main  # Событие запускается при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no user@your-server-ip "cd /path/to/deployment && git pull origin main && npm install && npm run build"
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock


